import * as BABYLON from "@babylonjs/core";

/**
 * BioSpecies — central catalog of 100+ collectible "robotic Pokemon"-style
 * pets. Each species is purely data; visuals are generated by
 * BioCreatureSystem.makeDescriptor() from `archetype` + `elementalType`.
 *
 * NOTE: keep the original five ids (`robofox`, `crystalbeetle`,
 * `hoverserpent`, `neonowl`, `voltfrog`) intact so old saves still resolve.
 */

export type Archetype =
  | "fox" | "cat" | "bunny" | "mouse" | "pup"
  | "beetle" | "frog" | "lizard" | "salamander"
  | "serpent" | "owl" | "bird" | "dragon"
  | "fish" | "crab" | "turtle"
  | "bear" | "monkey" | "golem"
  | "flutter" | "slime";

export type ElementalType =
  | "normal" | "flame" | "water" | "grass" | "electric"
  | "ice" | "psychic" | "evil" | "steel" | "crystal" | "dragon";

export type Rarity = "common" | "uncommon" | "rare" | "legendary";

export interface BioCreatureSpecies {
  id: string;
  name: string;
  archetype: Archetype;
  elementalType: ElementalType;
  rarity: Rarity;
  scale: number;
  baseCaptureChance: number;
  primary: BABYLON.Color3;
  secondary: BABYLON.Color3;
  emissive: BABYLON.Color3;
  /** Short tagline shown in the Bio Garden / Dex. */
  role: string;
}

// ---------------------------------------------------------------- palettes
// Default per-type colors used when a species omits explicit overrides.
const c = (r: number, g: number, b: number) => new BABYLON.Color3(r, g, b);

interface Palette { primary: BABYLON.Color3; secondary: BABYLON.Color3; emissive: BABYLON.Color3; }

export const TYPE_PALETTES: Record<ElementalType, Palette> = {
  normal:   { primary: c(0.78, 0.78, 0.82), secondary: c(0.92, 0.92, 0.95), emissive: c(0.85, 0.85, 0.9) },
  flame:    { primary: c(1.0, 0.35, 0.1),   secondary: c(1.0, 0.7, 0.25),   emissive: c(1.0, 0.5, 0.15) },
  water:    { primary: c(0.18, 0.5, 1.0),   secondary: c(0.5, 0.8, 1.0),    emissive: c(0.3, 0.7, 1.0) },
  grass:    { primary: c(0.25, 0.85, 0.35), secondary: c(0.6, 1.0, 0.5),    emissive: c(0.4, 1.0, 0.45) },
  electric: { primary: c(1.0, 0.95, 0.25),  secondary: c(1.0, 1.0, 0.55),   emissive: c(1.0, 1.0, 0.4) },
  ice:      { primary: c(0.55, 0.85, 1.0),  secondary: c(0.85, 0.95, 1.0),  emissive: c(0.6, 0.95, 1.0) },
  psychic:  { primary: c(1.0, 0.4, 0.85),   secondary: c(1.0, 0.7, 0.95),   emissive: c(1.0, 0.5, 0.9) },
  evil:     { primary: c(0.25, 0.18, 0.4),  secondary: c(0.45, 0.35, 0.6),  emissive: c(0.6, 0.3, 0.85) },
  steel:    { primary: c(0.55, 0.6, 0.7),   secondary: c(0.85, 0.88, 0.92), emissive: c(0.7, 0.85, 1.0) },
  crystal:  { primary: c(0.4, 0.9, 1.0),    secondary: c(0.85, 1.0, 1.0),   emissive: c(0.6, 1.0, 1.0) },
  dragon:   { primary: c(0.55, 0.25, 0.85), secondary: c(0.95, 0.6, 0.4),   emissive: c(0.8, 0.4, 1.0) },
};

/** UI hex tint per type (used for badges + dex tabs). */
export const TYPE_HEX: Record<ElementalType, string> = {
  normal: "#bdbdc4", flame: "#ff7038", water: "#4f9cff", grass: "#65d24a",
  electric: "#f7d633", ice: "#9ad9f7", psychic: "#f56fb8", evil: "#6b5392",
  steel: "#9aa6b3", crystal: "#7be1ff", dragon: "#a663ff",
};

/** Rarity to a 1-4 weight used by the wild spawn distribution. */
export const RARITY_WEIGHT: Record<Rarity, number> = {
  common: 8, uncommon: 4, rare: 2, legendary: 1,
};

const RARITY_HP: Record<Rarity, number> = { common: 60, uncommon: 75, rare: 95, legendary: 130 };
const RARITY_ATK: Record<Rarity, number> = { common: 10, uncommon: 13, rare: 17, legendary: 24 };
const RARITY_CAP: Record<Rarity, number> = { common: 0.55, uncommon: 0.42, rare: 0.28, legendary: 0.14 };

// --------------------------------------------------------------- compact spec
type SpecArgs = [
  id: string,
  name: string,
  archetype: Archetype,
  type: ElementalType,
  rarity: Rarity,
  scale: number,
  role: string,
  override?: Partial<Palette>,
];

function spec(...a: SpecArgs): BioCreatureSpecies {
  const [id, name, archetype, type, rarity, scale, role, override] = a;
  const pal = TYPE_PALETTES[type];
  return {
    id,
    name,
    archetype,
    elementalType: type,
    rarity,
    scale,
    baseCaptureChance: RARITY_CAP[rarity],
    primary: override?.primary ?? pal.primary,
    secondary: override?.secondary ?? pal.secondary,
    emissive: override?.emissive ?? pal.emissive,
    role,
  };
}

/** Base HP/ATK from rarity — exported for the capture flow. */
export function statsFromRarity(rarity: Rarity): { hp: number; attack: number; speed: number } {
  return { hp: RARITY_HP[rarity], attack: RARITY_ATK[rarity], speed: 1.0 };
}

// ------------------------------------------------------------------- catalog
// Hand-authored 100+ species. Keep ids stable; the original five are first.
export const BIO_SPECIES: BioCreatureSpecies[] = [
  // ---- Original five (do not rename / reorder ids) ----
  spec("robofox",        "RoboFox",         "fox",     "flame",     "common",   0.55, "Agile attacker"),
  spec("crystalbeetle",  "Crystal Beetle",  "beetle",  "crystal",  "common",   0.40, "Tough scout"),
  spec("hoverserpent",   "Hover Serpent",   "serpent", "grass",    "uncommon", 0.60, "Aerial striker"),
  spec("neonowl",        "Neon Owl",        "owl",     "psychic",  "uncommon", 0.50, "Recon drone"),
  spec("voltfrog",       "Volt Frog",       "frog",    "electric", "common",   0.45, "Shock support"),

  // ---- Fire ----
  spec("emberkit",       "Emberkit",        "fox",     "flame",     "common",   0.50, "Spits ember bursts"),
  spec("emberpup",       "Emberpup",        "pup",     "flame",     "common",   0.55, "Loyal flame hound"),
  spec("magmacat",       "Magmacat",        "cat",     "flame",     "uncommon", 0.50, "Searing pounce"),
  spec("scorchbunny",    "Scorchbunny",     "bunny",   "flame",     "uncommon", 0.45, "Hops on jet flares"),
  spec("infernodrake",   "Infernodrake",    "dragon",  "flame",     "rare",     0.75, "Fire-spit dragonling"),
  spec("ashbear",        "Ashbear",         "bear",    "flame",     "rare",     0.85, "Cinder-cloaked tank"),
  spec("lavalizard",     "Lavalizard",      "lizard",  "flame",     "common",   0.48, "Heat-armored runner"),
  spec("blazemoth",      "Blazemoth",       "flutter", "flame",     "uncommon", 0.55, "Wings of fire"),
  spec("pyroowl",        "Pyrowl",          "owl",     "flame",     "uncommon", 0.55, "Twilight burner"),
  spec("magmacrab",      "Magmacrab",       "crab",    "flame",     "uncommon", 0.60, "Shell of slag"),
  spec("infernoslime",   "Infernoslime",    "slime",   "flame",     "common",   0.45, "Living lava blob"),
  spec("phoenixhatch",   "Phoenixhatch",    "bird",    "flame",     "legendary",0.70, "Reborn at zero HP"),

  // ---- Water ----
  spec("aquakit",        "Aquakit",         "fox",     "water",    "common",   0.50, "Dives like a sluice"),
  spec("aquapup",        "Aquapup",         "pup",     "water",    "common",   0.55, "Splash dive support"),
  spec("hydraserpent",   "Hydraserpent",    "serpent", "water",    "rare",     0.70, "Tide-rider"),
  spec("tidalcat",       "Tidalcat",        "cat",     "water",    "uncommon", 0.50, "Surf-step striker"),
  spec("brinebear",      "Brinebear",       "bear",    "water",    "rare",     0.85, "Salt-sea tank"),
  spec("mistmoth",       "Mistmoth",        "flutter", "water",    "uncommon", 0.55, "Cloaks allies in fog"),
  spec("marlin",         "Marlin",          "fish",    "water",    "uncommon", 0.65, "Hover-fin striker"),
  spec("pufferbot",      "Pufferbot",       "fish",    "water",    "common",   0.45, "Inflates as shield"),
  spec("clamcrab",       "Clamcrab",        "crab",    "water",    "common",   0.55, "Pearl-blast scout"),
  spec("riverturtle",    "Riverturtle",     "turtle",  "water",    "common",   0.55, "Plated swimmer"),
  spec("splashfrog",     "Splashfrog",      "frog",    "water",    "common",   0.45, "Geyser-leap support"),
  spec("oceanowl",       "Oceanowl",        "owl",     "water",    "uncommon", 0.55, "Glides on sea spray"),
  spec("krakling",       "Krakling",        "fish",    "water",    "legendary",0.80, "Tentacled deep-runner"),

  // ---- Grass ----
  spec("mossfox",        "Mossfox",         "fox",     "grass",    "common",   0.50, "Camo-cloaked striker"),
  spec("vinepup",        "Vinepup",         "pup",     "grass",    "common",   0.55, "Vine-whip support"),
  spec("leafbeetle",     "Leafbeetle",      "beetle",  "grass",    "common",   0.40, "Pollen-burst scout"),
  spec("verdantcat",     "Verdantcat",      "cat",     "grass",    "uncommon", 0.50, "Blossom-bound striker"),
  spec("sproutfrog",     "Sproutfrog",      "frog",    "grass",    "common",   0.45, "Spore-cloud emitter"),
  spec("blossomflutter", "Blossomflutter",  "flutter", "grass",    "uncommon", 0.55, "Petal-storm wings"),
  spec("herbcrab",       "Herbcrab",        "crab",    "grass",    "common",   0.55, "Healing pollen aura"),
  spec("vinebear",       "Vinebear",        "bear",    "grass",    "rare",     0.85, "Moss-armored tank"),
  spec("leafdrake",      "Leafdrake",       "dragon",  "grass",    "rare",     0.75, "Sap-wing dragonling"),
  spec("seedmouse",      "Seedmouse",       "mouse",   "grass",    "common",   0.40, "Tiny pollen scout"),
  spec("forestowl",      "Forestowl",       "owl",     "grass",    "uncommon", 0.55, "Canopy hunter"),
  spec("verdantgolem",   "Verdantgolem",    "golem",   "grass",    "rare",     0.95, "Walking topiary"),

  // ---- Electric ----
  spec("zapfox",         "Zapfox",          "fox",     "electric", "common",   0.50, "Static-charge dasher"),
  spec("sparkpup",       "Sparkpup",        "pup",     "electric", "common",   0.55, "Tiny shock support"),
  spec("sparkbeetle",    "Sparkbeetle",     "beetle",  "electric", "common",   0.40, "Builds charge cells"),
  spec("voltcat",        "Voltcat",         "cat",     "electric", "uncommon", 0.50, "Coil-paw striker"),
  spec("plasmamouse",    "Plasmamouse",     "mouse",   "electric", "common",   0.40, "Cheek-cell zapper"),
  spec("currentbunny",   "Currentbunny",    "bunny",   "electric", "uncommon", 0.45, "Antenna-ear conductor"),
  spec("lightningserpent","Lightningserpent","serpent","electric", "rare",     0.70, "Bolt-bodied flyer"),
  spec("voltflutter",    "Voltflutter",     "flutter", "electric", "uncommon", 0.55, "Static-storm wings"),
  spec("surgegolem",     "Surgegolem",      "golem",   "electric", "rare",     0.95, "Walking transformer"),
  spec("jolturtle",      "Jolturtle",       "turtle",  "electric", "common",   0.55, "Plate-coil shell"),
  spec("ampbear",        "Ampbear",         "bear",    "electric", "rare",     0.85, "Storm-fur tank"),
  spec("dynacrab",       "Dynacrab",        "crab",    "electric", "uncommon", 0.55, "Claw-arc shocker"),

  // ---- Ice ----
  spec("frostfox",       "Frostfox",        "fox",     "ice",      "common",   0.50, "Frostbite dasher"),
  spec("frostpup",       "Frostpup",        "pup",     "ice",      "common",   0.55, "Snow-step support"),
  spec("frostbeetle",    "Frostbeetle",     "beetle",  "ice",      "common",   0.40, "Crystallized scout"),
  spec("snowcat",        "Snowcat",         "cat",     "ice",      "uncommon", 0.50, "Glacier prowler"),
  spec("icypup",         "Icypup",          "pup",     "ice",      "common",   0.55, "Sub-zero support"),
  spec("frosttoad",      "Frosttoad",       "frog",    "ice",      "common",   0.45, "Hailspit support"),
  spec("blizzardbear",   "Blizzardbear",    "bear",    "ice",      "rare",     0.90, "Storm-coat tank"),
  spec("hailmoth",       "Hailmoth",        "flutter", "ice",      "uncommon", 0.55, "Sleet-cloud wings"),
  spec("glaciercrab",    "Glaciercrab",     "crab",    "ice",      "uncommon", 0.55, "Frost-shell crusher"),
  spec("frostowl",       "Frostowl",        "owl",     "ice",      "uncommon", 0.55, "Polar glide hunter"),
  spec("crystaldrake",   "Crystaldrake",    "dragon",  "ice",      "rare",     0.75, "Glacial dragonling"),
  spec("rimeserpent",    "Rimeserpent",     "serpent", "ice",      "uncommon", 0.65, "Frost-arc flyer"),

  // ---- Psychic ----
  spec("mindcat",        "Mindcat",         "cat",     "psychic",  "uncommon", 0.50, "Telekinesis striker"),
  spec("telekfox",       "Telekfox",        "fox",     "psychic",  "uncommon", 0.50, "Mind-spike dasher"),
  spec("dreampup",       "Dreampup",        "pup",     "psychic",  "common",   0.55, "Sleep-aura support"),
  spec("psyowl",         "Psyowl",          "owl",     "psychic",  "uncommon", 0.55, "Mind's-eye hunter"),
  spec("esperflutter",   "Esperflutter",    "flutter", "psychic",  "uncommon", 0.55, "Resonance wings"),
  spec("phasebear",      "Phasebear",       "bear",    "psychic",  "rare",     0.85, "Reality-bend tank"),
  spec("mindlinkslime",  "Mindlinkslime",   "slime",   "psychic",  "common",   0.45, "Hive-mind blob"),
  spec("oraclepup",      "Oraclepup",       "pup",     "psychic",  "rare",     0.55, "Foresight support"),
  spec("astralmonkey",   "Astralmonkey",    "monkey",  "psychic",  "uncommon", 0.60, "Star-leap acrobat"),
  spec("dreamserpent",   "Dreamserpent",    "serpent", "psychic",  "rare",     0.70, "Lullaby-coil flyer"),
  spec("prismslime",     "Prismslime",      "slime",   "psychic",  "uncommon", 0.45, "Refracting blob"),

  // ---- Dark ----
  spec("voidcat",        "Voidcat",         "cat",     "evil",     "uncommon", 0.50, "Shadow-step striker"),
  spec("shadefox",       "Shadefox",        "fox",     "evil",     "uncommon", 0.50, "Twilight ambusher"),
  spec("dreadbeetle",    "Dreadbeetle",     "beetle",  "evil",     "common",   0.40, "Shadow-shell scout"),
  spec("gloomserpent",   "Gloomserpent",    "serpent", "evil",     "rare",     0.70, "Eclipse-coil flyer"),
  spec("nightowl",       "Nightowl",        "owl",     "evil",     "uncommon", 0.55, "Silent dive hunter"),
  spec("eclipsedrake",   "Eclipsedrake",    "dragon",  "evil",     "legendary",0.80, "Black-sun dragonling"),
  spec("voidpup",        "Voidpup",         "pup",     "evil",     "common",   0.55, "Wisp-trail support"),
  spec("shadowbear",     "Shadowbear",      "bear",    "evil",     "rare",     0.90, "Umbral cloak tank"),
  spec("hexmoth",        "Hexmoth",         "flutter", "evil",     "uncommon", 0.55, "Curse-dust wings"),
  spec("voidturtle",     "Voidturtle",      "turtle",  "evil",     "uncommon", 0.55, "Null-shell defender"),
  spec("shadeslime",     "Shadeslime",      "slime",   "evil",     "common",   0.45, "Inky absorber"),

  // ---- Steel ----
  spec("alloyfox",       "Alloyfox",        "fox",     "steel",    "common",   0.50, "Plated dasher"),
  spec("ironcat",        "Ironcat",         "cat",     "steel",    "uncommon", 0.50, "Plated pounce striker"),
  spec("steelpup",       "Steelpup",        "pup",     "steel",    "common",   0.55, "Riveted support"),
  spec("mechabeetle",    "Mechabeetle",     "beetle",  "steel",    "common",   0.40, "Drill-horn scout"),
  spec("gearowl",        "Gearowl",         "owl",     "steel",    "uncommon", 0.55, "Cogwheel hunter"),
  spec("alloyserpent",   "Alloyserpent",    "serpent", "steel",    "uncommon", 0.65, "Chain-link flyer"),
  spec("ironbear",       "Ironbear",        "bear",    "steel",    "rare",     0.95, "Riveted tank"),
  spec("ironcrab",       "Ironcrab",        "crab",    "steel",    "uncommon", 0.60, "Hydraulic-claw crusher"),
  spec("scrapgolem",     "Scrapgolem",      "golem",   "steel",    "uncommon", 0.95, "Junk-pile bruiser"),
  spec("voltgolem",      "Voltgolem",       "golem",   "steel",    "rare",     1.00, "Powerline juggernaut"),
  spec("rivetcrab",      "Rivetcrab",       "crab",    "steel",    "common",   0.55, "Bolt-shell scout"),
  spec("titanmonkey",    "Titanmonkey",     "monkey",  "steel",    "rare",     0.65, "Industrial swinger"),

  // ---- Crystal ----
  spec("prismcat",       "Prismcat",        "cat",     "crystal",  "uncommon", 0.50, "Refraction striker"),
  spec("crystalfox",     "Crystalfox",      "fox",     "crystal",  "uncommon", 0.50, "Shard-step dasher"),
  spec("gemslime",       "Gemslime",        "slime",   "crystal",  "common",   0.45, "Hardened blob"),
  spec("crystalpup",     "Crystalpup",      "pup",     "crystal",  "common",   0.55, "Faceted support"),
  spec("crystalflutter", "Crystalflutter",  "flutter", "crystal",  "uncommon", 0.55, "Geode wings"),
  spec("crystalbear",    "Crystalbear",     "bear",    "crystal",  "rare",     0.90, "Geode-armored tank"),
  spec("prismbeetle",    "Prismbeetle",     "beetle",  "crystal",  "common",   0.40, "Refractive scout"),
  spec("crystaldragon",  "Crystaldragon",   "dragon",  "crystal",  "legendary",0.80, "Faceted dragon king"),

  // ---- Dragon (rare/legendary spread) ----
  spec("voidskydragon",  "Voidskydragon",   "dragon",  "dragon",   "legendary",0.85, "Void-cloud sovereign"),
  spec("twincoildragon", "Twincoildragon",  "dragon",  "dragon",   "rare",     0.78, "Twin-element drake"),
  spec("hatchdragon",    "Hatchdragon",     "dragon",  "dragon",   "uncommon", 0.55, "Tiny dragonling"),
  spec("starfeatherdrake","Starfeatherdrake","dragon", "dragon",   "rare",     0.75, "Feathered cosmic drake"),

  // ---- Normal / utility ----
  spec("scoutcat",       "Scoutcat",        "cat",     "normal",   "common",   0.50, "Camp recon striker"),
  spec("courierpup",     "Courierpup",      "pup",     "normal",   "common",   0.55, "Cargo support"),
  spec("dashbunny",      "Dashbunny",       "bunny",   "normal",   "common",   0.45, "Hop-jet scout"),
  spec("runnermouse",    "Runnermouse",     "mouse",   "normal",   "common",   0.40, "Wire-tap scout"),
  spec("cargobear",      "Cargobear",       "bear",    "normal",   "uncommon", 0.85, "Pack-frame tank"),
  spec("signalflutter",  "Signalflutter",   "flutter", "normal",   "common",   0.55, "Beacon wings"),
  spec("surveyowl",      "Surveyowl",       "owl",     "normal",   "common",   0.55, "Cartography hunter"),
  spec("lightcrab",      "Lightcrab",       "crab",    "normal",   "common",   0.55, "Flare-claw scout"),
  spec("swiftserpent",   "Swiftserpent",    "serpent", "normal",   "common",   0.60, "Light-frame flyer"),
  spec("tinypup",        "Tinypup",         "pup",     "normal",   "common",   0.50, "Pocket-scale support"),
  spec("chipsalamander", "Chipsalamander",  "salamander","normal","common",    0.50, "Heat-sink lizard"),
  spec("dustcat",        "Dustcat",         "cat",     "normal",   "common",   0.50, "Vent-clearing scout"),
  spec("loaderape",      "Loaderape",       "monkey",  "normal",   "uncommon", 0.65, "Lift-frame hauler"),
];

// ---------------------------------------------------------------- helpers
export function getSpeciesById(id: string): BioCreatureSpecies | null {
  return BIO_SPECIES.find(s => s.id === id) ?? null;
}

export function speciesByType(type: ElementalType): BioCreatureSpecies[] {
  return BIO_SPECIES.filter(s => s.elementalType === type);
}

export const ALL_TYPES: ElementalType[] = [
  "normal", "flame", "water", "grass", "electric", "ice", "psychic", "evil", "steel", "crystal", "dragon",
];

/** Pick a random species weighted by rarity. */
export function pickWeightedSpecies(rng: () => number = Math.random): BioCreatureSpecies {
  let total = 0;
  for (const s of BIO_SPECIES) total += RARITY_WEIGHT[s.rarity];
  let pick = rng() * total;
  for (const s of BIO_SPECIES) {
    pick -= RARITY_WEIGHT[s.rarity];
    if (pick <= 0) return s;
  }
  return BIO_SPECIES[0];
}
