import * as BABYLON from "@babylonjs/core";
import { RobotDescriptor, applyTheme, createDefaultStyle } from "./RobotDesigner";

export const ROBOT_PRESETS: Record<string, RobotDescriptor> = {
  ScoutPrime: {
    name: "ScoutPrime",
    faction: "enemy",
    style: {
      archetype: "scout",
      scale: 1,
      torsoWidth: 1.1, torsoHeight: 1.5, torsoDepth: 0.7,
      headSize: 0.55, headShape: "box",
      armLength: 1.2, armThickness: 0.22, armStyle: "cylinder",
      legLength: 1.3, legThickness: 0.28, legStyle: "box",
      shoulderPadSize: 0.55, hipPadSize: 0.65,
      hasWings: false, wingSpan: 1.5, wingAngle: 0.35,
      hasCannons: false, cannonSize: 0.55,
      hasBackpack: false, backpackSize: 0.65,
      hasVisor: true, visorStyle: "slit",
      hasHorns: false, hornLength: 0.4,
      hasTail: false, tailLength: 1.5, tailSegments: 3,
      hasAntennae: false, antennaLength: 0.6,
      hasShield: false, shieldSize: 1.2,
      extraPlating: 0, asymmetry: 0,
      colors: {
        primary: new BABYLON.Color3(0.12, 0.25, 0.85),
        secondary: new BABYLON.Color3(0.75, 0.75, 0.8),
        emissive: new BABYLON.Color3(0.2, 0.9, 1.0),
      },
    },
  },
  BruteForge: {
    name: "BruteForge",
    faction: "enemy",
    style: {
      archetype: "brute",
      scale: 1.1,
      torsoWidth: 1.6, torsoHeight: 1.7, torsoDepth: 1.0,
      headSize: 0.6, headShape: "box",
      armLength: 1.4, armThickness: 0.32, armStyle: "box",
      legLength: 1.25, legThickness: 0.42, legStyle: "box",
      shoulderPadSize: 0.75, hipPadSize: 0.75,
      hasWings: false, wingSpan: 1.5, wingAngle: 0.35,
      hasCannons: true, cannonSize: 0.6,
      hasBackpack: false, backpackSize: 0.65,
      hasVisor: true, visorStyle: "full",
      hasHorns: true, hornLength: 0.35,
      hasTail: false, tailLength: 1.5, tailSegments: 3,
      hasAntennae: false, antennaLength: 0.6,
      hasShield: false, shieldSize: 1.2,
      extraPlating: 2, asymmetry: 0,
      colors: {
        primary: new BABYLON.Color3(0.6, 0.12, 0.1),
        secondary: new BABYLON.Color3(0.15, 0.15, 0.15),
        emissive: new BABYLON.Color3(1.0, 0.35, 0.05),
      },
    },
  },
  JetWarden: {
    name: "JetWarden",
    faction: "enemy",
    style: {
      archetype: "flyer",
      scale: 1,
      torsoWidth: 1.2, torsoHeight: 1.55, torsoDepth: 0.65,
      headSize: 0.55, headShape: "sphere",
      armLength: 1.15, armThickness: 0.22, armStyle: "tapered",
      legLength: 1.25, legThickness: 0.28, legStyle: "hoverpads",
      shoulderPadSize: 0.55, hipPadSize: 0.65,
      hasWings: true, wingSpan: 1.8, wingAngle: 0.35,
      hasCannons: true, cannonSize: 0.45,
      hasBackpack: true, backpackSize: 0.7,
      hasVisor: true, visorStyle: "round",
      hasHorns: false, hornLength: 0.4,
      hasTail: false, tailLength: 1.5, tailSegments: 3,
      hasAntennae: false, antennaLength: 0.6,
      hasShield: false, shieldSize: 1.2,
      extraPlating: 1, asymmetry: 0,
      colors: {
        primary: new BABYLON.Color3(0.12, 0.12, 0.15),
        secondary: new BABYLON.Color3(0.85, 0.85, 0.9),
        emissive: new BABYLON.Color3(0.5, 0.0, 1.0),
      },
    },
  },
  TankTitan: {
    name: "TankTitan",
    faction: "enemy",
    style: {
      archetype: "tank",
      scale: 1.2,
      torsoWidth: 1.8, torsoHeight: 1.8, torsoDepth: 1.1,
      headSize: 0.62, headShape: "box",
      armLength: 1.35, armThickness: 0.35, armStyle: "box",
      legLength: 1.15, legThickness: 0.48, legStyle: "box",
      shoulderPadSize: 0.85, hipPadSize: 0.85,
      hasWings: false, wingSpan: 1.5, wingAngle: 0.35,
      hasCannons: true, cannonSize: 0.7,
      hasBackpack: true, backpackSize: 0.8,
      hasVisor: false, visorStyle: "slit",
      hasHorns: true, hornLength: 0.5,
      hasTail: false, tailLength: 1.5, tailSegments: 3,
      hasAntennae: false, antennaLength: 0.6,
      hasShield: true, shieldSize: 1.5,
      extraPlating: 3, asymmetry: 0,
      colors: {
        primary: new BABYLON.Color3(0.12, 0.45, 0.2),
        secondary: new BABYLON.Color3(0.1, 0.1, 0.1),
        emissive: new BABYLON.Color3(0.1, 1.0, 0.4),
      },
    },
  },
  InsectoidStalker: {
    name: "InsectoidStalker",
    faction: "enemy",
    style: {
      archetype: "insectoid",
      scale: 0.9,
      torsoWidth: 0.9, torsoHeight: 1.2, torsoDepth: 0.8,
      headSize: 0.45, headShape: "sphere",
      armLength: 1.0, armThickness: 0.18, armStyle: "tapered",
      legLength: 1.4, legThickness: 0.22, legStyle: "digitigrade",
      shoulderPadSize: 0.35, hipPadSize: 0.45,
      hasWings: true, wingSpan: 1.0, wingAngle: 0.5,
      hasCannons: false, cannonSize: 0.4,
      hasBackpack: false, backpackSize: 0.5,
      hasVisor: true, visorStyle: "full",
      hasHorns: true, hornLength: 0.6,
      hasTail: true, tailLength: 1.8, tailSegments: 5,
      hasAntennae: true, antennaLength: 0.8,
      hasShield: false, shieldSize: 1.0,
      extraPlating: 0, asymmetry: 0.2,
      colors: {
        primary: new BABYLON.Color3(0.25, 0.35, 0.15),
        secondary: new BABYLON.Color3(0.4, 0.3, 0.1),
        emissive: new BABYLON.Color3(0.4, 1.0, 0.2),
      },
    },
  },
  HybridOmega: {
    name: "HybridOmega",
    faction: "enemy",
    style: {
      archetype: "hybrid",
      scale: 1.4,
      torsoWidth: 1.5, torsoHeight: 2.0, torsoDepth: 1.0,
      headSize: 0.7, headShape: "cone",
      armLength: 1.6, armThickness: 0.3, armStyle: "tapered",
      legLength: 1.5, legThickness: 0.4, legStyle: "digitigrade",
      shoulderPadSize: 0.8, hipPadSize: 0.7,
      hasWings: true, wingSpan: 2.2, wingAngle: 0.4,
      hasCannons: true, cannonSize: 0.65,
      hasBackpack: true, backpackSize: 0.9,
      hasVisor: true, visorStyle: "full",
      hasHorns: true, hornLength: 0.7,
      hasTail: true, tailLength: 2.0, tailSegments: 6,
      hasAntennae: true, antennaLength: 0.5,
      hasShield: true, shieldSize: 1.8,
      extraPlating: 3, asymmetry: 0.3,
      colors: {
        primary: new BABYLON.Color3(0.35, 0.15, 0.45),
        secondary: new BABYLON.Color3(0.1, 0.1, 0.12),
        emissive: new BABYLON.Color3(0.8, 0.0, 1.0),
      },
    },
  },
  OptimusForge: {
    name: "OptimusForge",
    faction: "enemy",
    style: applyTheme(
      { ...createDefaultStyle("transformer"), scale: 1.25 },
      "transformer"
    ),
  },
  HybridApex: {
    name: "HybridApex",
    faction: "enemy",
    style: applyTheme(
      { ...createDefaultStyle("hybrid"), scale: 1.5 },
      "hybrid"
    ),
  },
  CommanderOmega: {
    name: "CommanderOmega",
    faction: "enemy",
    style: {
      archetype: "tank",
      scale: 1.6,
      torsoWidth: 1.9, torsoHeight: 2.2, torsoDepth: 1.2,
      headSize: 0.75, headShape: "cone",
      armLength: 1.7, armThickness: 0.38, armStyle: "tapered",
      legLength: 1.6, legThickness: 0.5, legStyle: "digitigrade",
      shoulderPadSize: 1.0, hipPadSize: 0.9,
      hasWings: true, wingSpan: 2.5, wingAngle: 0.35,
      hasCannons: true, cannonSize: 0.8,
      hasBackpack: true, backpackSize: 1.0,
      hasVisor: true, visorStyle: "full",
      hasHorns: true, hornLength: 0.8,
      hasTail: false, tailLength: 1.5, tailSegments: 3,
      hasAntennae: false, antennaLength: 0.6,
      hasShield: true, shieldSize: 2.0,
      extraPlating: 3, asymmetry: 0,
      colors: {
        primary: new BABYLON.Color3(0.7, 0.15, 0.05),
        secondary: new BABYLON.Color3(0.15, 0.15, 0.2),
        emissive: new BABYLON.Color3(1.0, 0.4, 0.0),
      },
    },
  },
};

export const ALLY_PRESETS: Record<string, RobotDescriptor> = {
  MegaUnitX: {
    name: "MegaUnitX",
    faction: "ally",
    style: applyTheme(
      { ...createDefaultStyle("megaMan"), scale: 1.0 },
      "megaMan"
    ),
  },
  GuardianUnit: {
    name: "GuardianUnit",
    faction: "ally",
    style: {
      archetype: "ally",
      scale: 1.0,
      torsoWidth: 1.3, torsoHeight: 1.6, torsoDepth: 0.75,
      headSize: 0.55, headShape: "sphere",
      armLength: 1.2, armThickness: 0.24, armStyle: "cylinder",
      legLength: 1.3, legThickness: 0.3, legStyle: "box",
      shoulderPadSize: 0.6, hipPadSize: 0.6,
      hasWings: false, wingSpan: 1.5, wingAngle: 0.35,
      hasCannons: true, cannonSize: 0.5,
      hasBackpack: true, backpackSize: 0.6,
      hasVisor: true, visorStyle: "round",
      hasHorns: false, hornLength: 0.4,
      hasTail: false, tailLength: 1.5, tailSegments: 3,
      hasAntennae: false, antennaLength: 0.6,
      hasShield: true, shieldSize: 1.3,
      extraPlating: 1, asymmetry: 0,
      colors: {
        primary: new BABYLON.Color3(0.1, 0.5, 0.8),
        secondary: new BABYLON.Color3(0.8, 0.8, 0.85),
        emissive: new BABYLON.Color3(0, 0.8, 1.0),
      },
    },
  },
  MedicDrone: {
    name: "MedicDrone",
    faction: "ally",
    style: {
      archetype: "ally",
      scale: 0.8,
      torsoWidth: 1.0, torsoHeight: 1.2, torsoDepth: 0.6,
      headSize: 0.5, headShape: "sphere",
      armLength: 0.9, armThickness: 0.18, armStyle: "tapered",
      legLength: 1.0, legThickness: 0.22, legStyle: "hoverpads",
      shoulderPadSize: 0.4, hipPadSize: 0.45,
      hasWings: false, wingSpan: 1.2, wingAngle: 0.3,
      hasCannons: false, cannonSize: 0.4,
      hasBackpack: true, backpackSize: 0.5,
      hasVisor: true, visorStyle: "round",
      hasHorns: false, hornLength: 0.3,
      hasTail: false, tailLength: 1.0, tailSegments: 3,
      hasAntennae: true, antennaLength: 0.5,
      hasShield: false, shieldSize: 1.0,
      extraPlating: 0, asymmetry: 0,
      colors: {
        primary: new BABYLON.Color3(0.8, 0.85, 0.9),
        secondary: new BABYLON.Color3(0.9, 0.2, 0.2),
        emissive: new BABYLON.Color3(0.2, 1.0, 0.4),
      },
    },
  },
  ScoutCompanion: {
    name: "ScoutCompanion",
    faction: "ally",
    style: {
      archetype: "ally",
      scale: 0.85,
      torsoWidth: 1.0, torsoHeight: 1.3, torsoDepth: 0.6,
      headSize: 0.5, headShape: "box",
      armLength: 1.0, armThickness: 0.2, armStyle: "cylinder",
      legLength: 1.2, legThickness: 0.25, legStyle: "digitigrade",
      shoulderPadSize: 0.45, hipPadSize: 0.5,
      hasWings: false, wingSpan: 1.3, wingAngle: 0.35,
      hasCannons: true, cannonSize: 0.4,
      hasBackpack: false, backpackSize: 0.5,
      hasVisor: true, visorStyle: "slit",
      hasHorns: false, hornLength: 0.3,
      hasTail: false, tailLength: 1.2, tailSegments: 3,
      hasAntennae: false, antennaLength: 0.5,
      hasShield: false, shieldSize: 1.0,
      extraPlating: 0, asymmetry: 0,
      colors: {
        primary: new BABYLON.Color3(0.3, 0.6, 0.3),
        secondary: new BABYLON.Color3(0.7, 0.7, 0.6),
        emissive: new BABYLON.Color3(0.3, 1.0, 0.6),
      },
    },
  },
  // Legendary endgame ally — a humanoid mini-General companion granted
  // ONLY after the player both defeats General Voidcrown in the Swarms
  // Lair (Level 7) AND frees every caged synthetic + every caged lab
  // animal. Dark void/blood palette mirrors the boss; smaller scale +
  // horned crown silhouette so the player reads it as "the General's
  // little brother — now on our side". Routed through the same robot
  // factory as every other companion (no humanoid plumbing needed) but
  // tuned to a tall biped silhouette via narrow torso + long limbs.
  MiniGeneralVoidcrown: {
    name: "MiniGeneralVoidcrown",
    faction: "ally",
    style: {
      archetype: "ally",
      scale: 1.15,
      torsoWidth: 1.15, torsoHeight: 1.7, torsoDepth: 0.7,
      headSize: 0.55, headShape: "sphere",
      armLength: 1.35, armThickness: 0.26, armStyle: "tapered",
      legLength: 1.5, legThickness: 0.32, legStyle: "digitigrade",
      shoulderPadSize: 0.75, hipPadSize: 0.65,
      hasWings: false, wingSpan: 1.5, wingAngle: 0.3,
      hasCannons: true, cannonSize: 0.55,
      hasBackpack: true, backpackSize: 0.65,
      hasVisor: true, visorStyle: "full",
      hasHorns: true, hornLength: 0.7,
      hasTail: false, tailLength: 1.2, tailSegments: 3,
      hasAntennae: false, antennaLength: 0.4,
      hasShield: true, shieldSize: 1.2,
      extraPlating: 2, asymmetry: 0.05,
      colors: {
        primary:   new BABYLON.Color3(0.10, 0.04, 0.10),
        secondary: new BABYLON.Color3(0.55, 0.05, 0.10),
        emissive:  new BABYLON.Color3(0.95, 0.10, 0.35),
      },
    },
  },
  // Premium endgame unlock — large winged hybrid that rides the player's
  // orbit. Heavy on plating, wings + tail + horns for that "robot dragon"
  // silhouette. Spawned through the SPECIALS upgrade tab.
  RoboDragon: {
    name: "RoboDragon",
    faction: "ally",
    style: {
      archetype: "hybrid",
      scale: 1.6,
      torsoWidth: 1.6, torsoHeight: 1.8, torsoDepth: 1.2,
      headSize: 0.75, headShape: "cone",
      armLength: 1.5, armThickness: 0.3, armStyle: "tapered",
      legLength: 1.4, legThickness: 0.4, legStyle: "digitigrade",
      shoulderPadSize: 0.85, hipPadSize: 0.8,
      hasWings: true, wingSpan: 3.2, wingAngle: 0.45,
      hasCannons: true, cannonSize: 0.7,
      hasBackpack: true, backpackSize: 0.9,
      hasVisor: true, visorStyle: "full",
      hasHorns: true, hornLength: 0.85,
      hasTail: true, tailLength: 2.6, tailSegments: 7,
      hasAntennae: false, antennaLength: 0.5,
      hasShield: true, shieldSize: 1.6,
      extraPlating: 3, asymmetry: 0.15,
      colors: {
        primary: new BABYLON.Color3(0.55, 0.10, 0.10),
        secondary: new BABYLON.Color3(0.18, 0.05, 0.05),
        emissive: new BABYLON.Color3(1.0, 0.45, 0.05),
      },
    },
  },
};

export const PET_PRESETS: Record<string, RobotDescriptor> = {
  SparkPup: {
    name: "SparkPup",
    faction: "pet",
    style: {
      archetype: "pet",
      scale: 0.45,
      torsoWidth: 0.7, torsoHeight: 0.6, torsoDepth: 0.9,
      headSize: 0.45, headShape: "sphere",
      armLength: 0.5, armThickness: 0.12, armStyle: "cylinder",
      legLength: 0.5, legThickness: 0.15, legStyle: "box",
      shoulderPadSize: 0.2, hipPadSize: 0.25,
      hasWings: false, wingSpan: 0.8, wingAngle: 0.3,
      hasCannons: false, cannonSize: 0.3,
      hasBackpack: false, backpackSize: 0.4,
      hasVisor: true, visorStyle: "round",
      hasHorns: false, hornLength: 0.2,
      hasTail: true, tailLength: 0.6, tailSegments: 4,
      hasAntennae: true, antennaLength: 0.3,
      hasShield: false, shieldSize: 0.8,
      extraPlating: 0, asymmetry: 0,
      colors: {
        primary: new BABYLON.Color3(0.9, 0.7, 0.1),
        secondary: new BABYLON.Color3(0.95, 0.85, 0.5),
        emissive: new BABYLON.Color3(1.0, 0.9, 0.2),
      },
    },
  },
  NeonCat: {
    name: "NeonCat",
    faction: "pet",
    style: {
      archetype: "pet",
      scale: 0.4,
      torsoWidth: 0.6, torsoHeight: 0.5, torsoDepth: 0.8,
      headSize: 0.4, headShape: "sphere",
      armLength: 0.4, armThickness: 0.1, armStyle: "tapered",
      legLength: 0.45, legThickness: 0.12, legStyle: "digitigrade",
      shoulderPadSize: 0.15, hipPadSize: 0.2,
      hasWings: false, wingSpan: 0.6, wingAngle: 0.3,
      hasCannons: false, cannonSize: 0.2,
      hasBackpack: false, backpackSize: 0.3,
      hasVisor: true, visorStyle: "slit",
      hasHorns: true, hornLength: 0.15,
      hasTail: true, tailLength: 0.8, tailSegments: 5,
      hasAntennae: false, antennaLength: 0.3,
      hasShield: false, shieldSize: 0.6,
      extraPlating: 0, asymmetry: 0,
      colors: {
        primary: new BABYLON.Color3(0.15, 0.1, 0.25),
        secondary: new BABYLON.Color3(0.3, 0.2, 0.4),
        emissive: new BABYLON.Color3(0.8, 0.0, 1.0),
      },
    },
  },
  HoverOrb: {
    name: "HoverOrb",
    faction: "pet",
    style: {
      archetype: "pet",
      scale: 0.35,
      torsoWidth: 0.5, torsoHeight: 0.5, torsoDepth: 0.5,
      headSize: 0.6, headShape: "sphere",
      armLength: 0.3, armThickness: 0.08, armStyle: "tapered",
      legLength: 0.3, legThickness: 0.1, legStyle: "hoverpads",
      shoulderPadSize: 0.15, hipPadSize: 0.15,
      hasWings: true, wingSpan: 0.5, wingAngle: 0.2,
      hasCannons: false, cannonSize: 0.2,
      hasBackpack: false, backpackSize: 0.3,
      hasVisor: true, visorStyle: "full",
      hasHorns: false, hornLength: 0.2,
      hasTail: false, tailLength: 0.5, tailSegments: 3,
      hasAntennae: true, antennaLength: 0.4,
      hasShield: false, shieldSize: 0.5,
      extraPlating: 0, asymmetry: 0,
      colors: {
        primary: new BABYLON.Color3(0.1, 0.8, 0.9),
        secondary: new BABYLON.Color3(0.6, 0.9, 1.0),
        emissive: new BABYLON.Color3(0, 1.0, 1.0),
      },
    },
  },
};
